### ISSUE TITLE
Remove parts of Readme in favor of wiki

### ISSUE THREAD

**Issue by cnlohr** [cnlohr/ch32v003fun#127]

**Comment by mengstr** [comment]
Maybe mentioning that the 20 ns resolution @48MHz is really closer to 21 or add a few decimals to it could be a good thing? My mind went straight to "_ohhh, nice even number, that seems really useful!_" before realising that it actually is 20.83333...

**Comment by cnlohr** [comment]
Where is that mention?

**Comment by mengstr** [comment]
It currently says that the resolution is 20ns, but I think it would be nice to show a few decimals in order to not have people believe that it's exactly 20ns (as it would be if the chip was run at 50MHz). I know the formulas and all is there, but my eyes was drawn to the nice numbers. ;)

https://github.com/cnlohr/ch32v003fun/wiki/Time#time-by-systick

<img width="807" alt="systick" src="https://github.com/cnlohr/ch32v003fun/assets/325326/23140a72-bc3c-4a04-b869-76841332c784">

**Comment by cnlohr** [comment]
fixed
