### ISSUE TITLE
TINYVECTOR compile flag causes problems when target is CH32V203

### ISSUE THREAD

**Issue by renzenicolai** [cnlohr/ch32v003fun#321]
Compiling using the -DTINYVECTOR compile flag causes the program to fail to run at startup when compiling for CH32V203. Weirdly the program does run once after flashing.

Maybe this compile flag should give an error or warning if the target is the CH32V203.

**Comment by eeucalyptus** [comment]
The fact that it does work the first time probably has to do with the bootloader somehow jumping into the code after the flashing, instead of relying on the reset handler as after a reset. But tbh I'm not deep enough into that code to say what really happened there. The option is now called `FUNCONF_TINYVECTOR` and it has been reworked quite thoroughly since this. I would consider this issue as obsolete.
