### ISSUE TITLE
Cannot compile standard libraries?

### ISSUE THREAD

**Issue by Ganesharyal24894** [cnlohr/ch32v003fun#330]
I don't know why I cannot compile standard libraries in my code. I want to use rand() function but it shows undefined reference to rand() I thought this is because of the -nostdlibs flag so I commented that flag but now it says cannot find -lc,lgloss,crt0.o?? Is it because the toolchain does not comes with these standard libraries?? I have tried in both windows(WSL) and ubuntu and the output is same how do I solve this error I could not find anything related to this on the internet please help if you guys have any idea on this...

**Comment by sellicott** [comment]
I'm going to start by advising *not* to do this, particularly if what you are after is `rand`, there are better `rand` implementations than the one in the standard library. If you just need rand from the standard library, I recommend looking into [pcg random](https://www.pcg-random.org/) or [an xorshift variant](https://en.wikipedia.org/wiki/Xorshift). Either are easy to incorporate into a project without additional dependencies and provide better statistical properties than the standard library implementation.

In order to get standard libraries to work, you will need a standard library that supports microcontrollers. However, it's not quite that simple (you can't just drop it in and expect it to work) since the library doesn't know how to interact with the hardware. Typically, people use either [newlib](https://sourceware.org/newlib/) or [picolibc](https://keithp.com/picolibc/) (personally, I've only used newlib sometime in the past). You will need to implement a certain subset of "stub" functions that allow the library to interact with the underlying hardware in the way you want (these basically implement functions that are usually provided by the linux kernel). [Hackaday article](https://hackaday.com/2021/07/19/the-newlib-embedded-c-standard-library-and-how-to-use-it/), [newlib documentation](https://sourceware.org/newlib/libc.html#Stubs).

Hope this is helpful.
Soli Deo Gloria

**Comment by prosper00** [comment]
If it's *just* rand you need, there are a ton of ways to get a pseudo-random number that's usable for many cases where you'd normally use stdlib (e.g. NOT secure crypto).

Something like this is easy to copy/paste into an application:
```
static uint16_t random(void){ 
  static unsigned long lfsr = 0xfeedfaceUL; // or seed this from a floating ADC, or some other hard-to-predict value
  if(lfsr & 1) lfsr = (lfsr >>1) ^ LFSR_MASK ; else lfsr >>= 1;
  return(lfsr);
}
```

**Comment by cnlohr** [comment]
The reason things like `rand()` are not included in ch32v003fun is because they are so context-dependent, i.e. 

You could use a reference implementation like this one:

https://github.com/dolthub/musl/blob/8aec69db0851e6e197e69b8dca8da3344190f6dd/src/prng/rand.c#L11

It's not very good though, and, because the ch32v003 doesn't have a multiply, it's going to be slow.

**Comment by cnlohr** [comment]
Also for more background, these sorts of features go back and forth a lot, see this : https://github.com/dolthub/musl/commit/c79cd27e9e81eb5e223728094f1233ee2fc12dda

**Comment by Ganesharyal24894** [comment]
Thank you everyone for your guidance, it is very helpful.
