### ISSUE TITLE
printf via UART sends out unreadable character when FUNCONF_SYSTEM_CORE_CLOCK is below 24MHz

### ISSUE THREAD

**Issue by hientv1999** [cnlohr/ch32v003fun#399]
As the title mentioned, when I lower the FUNCONF_SYSTEM_CORE_CLOCK to 16MHz and 8MHz, any printf text will turn into weird characters. I have reduced FUNCONF_UART_PRINTF_BAUD to 9600 but still no help.. I don't understand why it does this.

Also I wonder how low I can safely reduce FUNCONF_SYSTEM_CORE_CLOCK  to? Last time when using noneos framework I reduce this value to 750KHz and I brick the MCU. Now I don't want to risk it again.

**Comment by eeucalyptus** [comment]
The `FUNCONF_SYSTEM_CORE_CLOCK` doesn't set the clock speed itself, but indicates the core clock speed to eg. delays and baudrate calculation.

In order to reduce the clock speed you can't just set the `FUNCONF_SYSTEM_CORE_CLOCK` to whatever core frequency you need. You also have to set the AHB prescalar to reduce the core clock (and all other clocks proportionally). 
This can be done by setting the RCC_CFGR0.HPRE (page 18 in the reference manual). 

Check this example:

```
#include "ch32v003fun.h"
int main()
{
        SystemInit();
        RCC->CFGR0 |= 0b1010 << 4;
        while(1) {
            // core running at 3 MHz
        }

```

Of course you will still have to set the `FUNCONF_SYSTEM_CORE_CLOCK` in the funconfig.h to 3MHz. 

You don't have to worry about bricking the device this way, as long as you can supply the power via the programmer. Because then you can just run `minichlink -u` to unbrick. This works because there is a tiny time slot after power on before the main runs in where the debugger can attach and interrupt the execution.

**Comment by hientv1999** [comment]
> The `FUNCONF_SYSTEM_CORE_CLOCK` doesn't set the clock speed itself, but indicates the core clock speed to eg. delays and baudrate calculation.
> 
> In order to reduce the clock speed you can't just set the `FUNCONF_SYSTEM_CORE_CLOCK` to whatever core frequency you need. You also have to set the AHB prescalar to reduce the core clock (and all other clocks proportionally). This can be done by setting the RCC_CFGR0.HPRE (page 18 in the reference manual).
> 
> Check this example:
> 
> ```
> #include "ch32v003fun.h"
> int main()
> {
>         SystemInit();
>         RCC->CFGR0 |= 0b1010 << 4;
>         while(1) {
>             // core running at 3 MHz
>         }
> }
> ```
> 
> Of course you will still have to set the `FUNCONF_SYSTEM_CORE_CLOCK` in the funconfig.h to 3MHz.
> 
> You don't have to worry about bricking the device this way, as long as you can supply the power via the programmer. Because then you can just run `minichlink -u` to unbrick. This works because there is a tiny time slot after power on before the main runs in where the debugger can attach and interrupt the execution.

Hi,

Thank you very much for your detail explanation. What is the actual purpose of minichlink -u command? And at which directory I can run it from? Right now running it directly from Command Prompt in my project folder doesn't work. It returns "'minichlink' is not recognized as an internal or external command,     operable program or batch file."

**Comment by TommyMurphyTM1234** [comment]
> What is the actual purpose of minichlink -u command?

Refer to the `minichlink` readme and sources:

- https://github.com/cnlohr/ch32v003fun/tree/master/minichlink
- https://github.com/cnlohr/ch32v003fun/blob/bbad78a904a952a04e9edbd13863f8b0331a26fd/minichlink/minichlink.c#L680
- https://github.com/cnlohr/ch32v003fun/blob/bbad78a904a952a04e9edbd13863f8b0331a26fd/minichlink/minichlink.c#L241-L246
- https://github.com/cnlohr/ch32v003fun/blob/bbad78a904a952a04e9edbd13863f8b0331a26fd/minichlink/minichlink.c#L2034-L2035
- https://github.com/cnlohr/ch32v003fun/blob/bbad78a904a952a04e9edbd13863f8b0331a26fd/minichlink/minichlink.c#L1858-L1928

 > And at which directory I can run it from? 

From here or add it to your `PATH` etc.

- https://github.com/cnlohr/ch32v003fun/tree/master/minichlink
